project:
  type: website

website:
  title: "Justyn Time"
  # site-url: "https://becausejustyn.netlify.app/"
  repo-url: "https://github.com/becausejustyn/personal-blog"
  twitter-card:
    creator: "@becausejustyn"
  navbar:
    title: false
    background: primary
    search: true
    left: 
      - text: "{{< fa house-user >}} Home"
        href: about.qmd
      - text: "{{< fa newspaper >}} Blog"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/becausejustyn
      - icon: twitter
        href: https://twitter.com/becausejustyn
format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]



